version: '3.8'

services:
  weather-app:
    build: .
    ports:
      - "6065:6065"
    volumes:
      - weather_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=6065
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weather-app
    restart: unless-stopped

volumes:
  weather_data:
